### ISSUE TITLE
Problem with Image alignment

### ISSUE THREAD

**Issue by cab-1729** [LukeSmithxyz/lugo#1]
I'm not familiar with Hugo so I don't know the cause.

Images on you blog tend to overlap with the text.
Your article on [Monero](https://lukesmith.xyz/articles/monero-maximalism-or-how-bitcoin-is-a-coin):

![image](https://user-images.githubusercontent.com/60106638/168456479-8239e4e5-fcc5-40f5-9fac-fc3a996cddc6.png)

Your article on [Licensing](https://lukesmith.xyz/articles/why-i-use-the-gpl-and-not-cuck-licenses)
![image](https://user-images.githubusercontent.com/60106638/168456491-0b67f897-36b5-41b6-a717-649166d95b03.png)

It becomes even worse if the browser does not take full screen:

![image](https://user-images.githubusercontent.com/60106638/168456515-f5ba9c55-494e-4142-8389-511053a33a73.png)

These images are taken using the Tor browser but the same problem occurs on Brave and Firefox.

When I'm downloading your articles I change remove ```class="resright"``` from your __figure__ tags.

![image](https://user-images.githubusercontent.com/60106638/168456627-18a3cffd-b8da-424e-a275-9ded591f3259.png)

That stops the overlap but makes the image centered which is probably not your intent.

**Comment by LukeSmithxyz** [comment]
My current website is not using hugo or this repository.
