### ISSUE TITLE
simplify lugo with base templates and blocks

### ISSUE THREAD

**Issue by shaharbest** [LukeSmithxyz/lugo#10]
problem:
in partials directory `header.html` contain the opening tags `<body>` and `<main>` and `footer.html` contain `</article>`, `</main>` and `</body>`.

It's much easier to follow and maintain the project if all opening tags will be closed at the same template.

[based.cooking](https://based.cooking/) homepage contain an extra unnecessary `</article>` because of the difficulty of following the page final structure.

I recommend embracing the base templates and blocks ([docs](https://gohugo.io/templates/base/#define-the-base-template))

**Comment by LukeSmithxyz** [comment]
Yeah, I'll probably change this when I get the chance if someone doesn't PR it.
