### ISSUE TITLE
Add explicit declarations for color emoji fonts in CSS

### ISSUE THREAD

**Issue by ghost** [LukeSmithxyz/lugo#6]
Color emoji fonts are not currently specified in the stylesheet, thus browsers might override an emoji with a dingbat, if the latter is available in the font specified by the user's browser.

The following screenshots show the issue:
Without any font declaration:
![myvideos](https://user-images.githubusercontent.com/108974501/178713626-9d9397b0-cae9-4ce1-b860-c4feb701902c.PNG)

With `font-family: 'Segoe UI Emoji'` added to the `body` tag:
![myvideosemoji](https://user-images.githubusercontent.com/108974501/178714184-3a0adb2c-2e67-43c7-8e64-78161a49b9d3.PNG)

Adding a line such as `font-family: 'Apple Color Emoji', 'Segoe UI Emoji', 'Noto Color Emoji';` should be enough for most platforms.

The downside of this solution is that it does not allow people to easily view your site with the font of their choice, which may or may not be what you want.

**Comment by LukeSmithxyz** [comment]
K. I'll make this change.
